---
root: true

parser: "@typescript-eslint/parser"

extends:
  # https://github.com/yannickcr/eslint-plugin-react
  - plugin:react/recommended
  - eslint:recommended
  - plugin:@next/next/recommended

plugins:
  - react

settings:
  react:
    version: detect

env:
  es6: true
  browser: true
  node: true

globals:
  fetch: true
  navigator: true
  __DEV__: true
  XMLHttpRequest: true
  React$Element: true
  Generator: true

parserOptions:
  ecmaVersion: 2017
  sourceType: module
  ecmaFeatures:
    jsx: true

rules:
  semi: [error, never]
  no-case-declarations: off

  ### From error to warning ###
  # was not working when used with flow prop types
  no-unused-vars: off # TODO: warn later
  react/no-unescaped-entities: off
  react/no-unused-prop-types: warn
  react/no-unknown-property: [2, { ignore: [ jsx ] }]
  react/react-in-jsx-scope: off
  react/prop-types: off # TODO: open later
