/* eslint sort-keys: "error" */
module.exports = {
  'amo': require('./amo.js'),
  'apm': require('./apm.js'),
  'appveyor': require('./appveyor.js'),
  'bundlephobia': require('./bundlephobia.js'),
  'chrome-web-store': require('./chrome-web-store.js'),
  'circleci': require('./circleci.js'),
  'codecov': require('./codecov.js'),
  'coveralls': require('./coveralls.js'),
  'crates': require('./crates.js'),
  'david': require('./david.js'),
  'docker': require('./docker.js'),
  'github': require('./github.js'),
  'homebrew': require('./homebrew.js'),
  'npm': require('./npm.js'),
  'nuget': require('./nuget.js'),
  'opencollective': require('./opencollective.js'),
  'packagephobia': require('./packagephobia.js'),
  'packagist': require('./packagist.js'),
  'pypi': require('./pypi.js'),
  'rubygems': require('./rubygems.js'),
  'runkit': require('./runkit.js'),
  'travis': require('./travis.js'),
  'uptime-robot': require('./uptime-robot.js')
}
